server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-wispy-heart-ahwgglaz-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_iSOaxk1TYZp8}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: cGFydGFsYWNhZGVtaWNvU2FuQWd1c3RpbkNhbXB1czIwMjVTZWN1cmVLZXk=
  expiration: 86400000

openai:
  api:
    key: ${GEMINI_API_KEY:${OPENAI_API_KEY:}}
    url: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
    model: "gemini-2.5-flash"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always


